#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Pour le site web
home:
    path: /
    controller: App\Controller\HomeController::index

property.index:
    path: /biens
    controller: App\Controller\PropertyController::index

property.show:
    path: /biens/{slug}-{id}
    controller: App\Controller\PropertyController::show
    requirements:
        slug: '[a-z0-9\-]*'

# Pour la partie administration
admin.property.index:
    path: /admin
    controller: App\Controller\Admin\AdminPropertyController::index

admin.property.edit:
    path: /admin/{id}/edit
    controller: App\Controller\Admin\AdminPropertyController::edit
    requirements:
        id: '[0-9]*'
    methods: GET|POST

admin.property.new:
    path: /admin/bien/create
    controller: App\Controller\Admin\AdminPropertyController::new

admin.property.delete:
    path: /admin/{id}/delete
    controller: App\Controller\Admin\AdminPropertyController::delete
    requirements:
        id: '[0-9]*'
    methods: DELETE

# Pour la partie login
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout


