#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

property.index:
  path: /biens
  controller: App\Controller\PropertyController::index

property.show:
  path: /biens/{slug}-{id}
  controller: App\Controller\PropertyController::show
  requirements:
    slug: '[a-z0-9\-]*'

admin.property.index:
  path: /admin
  controller: App\Controller\Admin\AdminPropertyController::index

admin.property.edit:
  path: /admin/{id}/edit
  controller: App\Controller\Admin\AdminPropertyController::edit
  requirements:
    id: '[0-9]*'

